- name: Install Java
  yum:
    state: latest
    name: '{{ item }}'
  loop:
    - java
    - mysql

- name: Download tomcat 8
  get_url:
    url: "{{ TOMCAT_URL }}"
    dest: /opt/

- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/
    remote_src: true

- name: Deploy webapp
  copy:
    src: ./student.war
    dest: /opt/{{TOMCAT_DIR}}/webapps/student.war

- name: Upload configuration file
  copy:
    src: ./context.xml
    dest: /opt/{{TOMCAT_DIR}}/conf/context.xml

- name: Store my-sql connector in lib
  get_url:
    url: '{{MYSQL_LIB_URL}}'
    dest: /opt/{{TOMCAT_DIR}}/lib/

- name: Create Daemon for tomcat
  copy:
    src: ./tomcat-init
    dest: /etc/init.d/tomcatd
    mode: '0777'

- name: Reload the daemon
  shell: systemctl daemon-reload

- name: restart tomcat
  service:
    name: tomcatd
    state: restarted 
    enabled: true